# Use an official lightweight Python image
FROM python:3.13-slim

# Set working directory inside the container
WORKDIR /app

# Copy requirements first to leverage Docker layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY *.py .

# Expose the default Gradio port
EXPOSE 8000

# Command to run your Gradio application
CMD ["python", "app.py"]
# docker run -d -p 8000:8000 fastapi-app
# docker run -p 8000:8000 ner-app
# docker build . -t ner-app

